name: CI

on: [push, pull_request]

jobs:

  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
          apt-get update && apt-get install -y build-essential
          make SERVER_CFLAGS='-Werror'
      - name: Compress valkey-server binary
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -czvf valkey-server-linux-x64.tar.gz src/valkey-server COPYING
      - name: Upload redis-server binary
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: build-linux-x64
          path: valkey-server-linux-x64.tar.gz

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
          sudo apt-get update && sudo apt-get install libc6-dev-i386
          make SERVER_CFLAGS='-Werror' 32bit
      - name: Compress valkey-server binary
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -czvf valkey-server-linux-x86.tar.gz src/valkey-server COPYING
      - name: Upload redis-server binary
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: build-linux-x86
          path: valkey-server-linux-x86.tar.gz


  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
          apt-get update && apt-get install -y build-essential
          make SERVER_CFLAGS='-Werror'
      - name: Compress valkey-server binary
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -czvf valkey-server-linux-arm64.tar.gz src/valkey-server COPYING
      - name: Upload redis-server binary
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: build-linux-arm64
          path: valkey-server-linux-arm64.tar.gz


  build-macos-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make SERVER_CFLAGS='-Werror'
      - name: Compress valkey-server binary
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -czvf valkey-server-macos-x64.tar.gz src/valkey-server COPYING
      - name: Upload redis-server binary
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: build-macos-x64
          path: valkey-server-macos-x64.tar.gz

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make SERVER_CFLAGS='-Werror'
      - name: Compress valkey-server binary
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -czvf valkey-server-macos-arm64.tar.gz src/valkey-server COPYING
      - name: Upload redis-server binary
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: build-macos-arm64
          path: valkey-server-macos-arm64.tar.gz

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux-x64, build-linux-x86, build-linux-arm64, build-macos-x64, build-macos-arm64]
    if: startsWith(github.ref, 'refs/tags/v')  # Run only if a tag is present
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/build-linux-x64/valkey-server-linux-x64.tar.gz
          asset_name: valkey-server-linux-x64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/build-linux-x86/valkey-server-linux-x86.tar.gz
          asset_name: valkey-server-linux-x86-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/build-linux-arm64/valkey-server-linux-arm64.tar.gz
          asset_name: valkey-server-linux-arm64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/build-macos-x64/valkey-server-macos-x64.tar.gz
          asset_name: valkey-server-macos-x64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/build-macos-arm64/valkey-server-macos-arm64.tar.gz
          asset_name: valkey-server-macos-arm64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream